"""Posts a single image with a caption to a personal LinkedIn profile via the Posts API.

Usage:
    python src/linkedin_post.py path/to/image.jpg "Caption text"

Required environment variable (see .env.example):
    LINKEDIN_ACCESS_TOKEN — generated by src/linkedin_auth.py
"""

import os
import sys

import requests
from dotenv import load_dotenv

API_VERSION = "202607"


def _headers(access_token: str, content_type: str | None = "application/json") -> dict:
    headers = {
        "Authorization": f"Bearer {access_token}",
        "LinkedIn-Version": API_VERSION,
        "X-Restli-Protocol-Version": "2.0.0",
    }
    if content_type:
        headers["Content-Type"] = content_type
    return headers


def get_person_urn(access_token: str) -> str:
    response = requests.get(
        "https://api.linkedin.com/v2/userinfo",
        headers=_headers(access_token, content_type=None),
        timeout=30,
    )
    body = response.json()

    if response.status_code != 200 or "sub" not in body:
        raise RuntimeError(f"Could not fetch LinkedIn profile (HTTP {response.status_code}): {body}")

    return f"urn:li:person:{body['sub']}"


def initialize_image_upload(access_token: str, person_urn: str) -> tuple[str, str]:
    response = requests.post(
        "https://api.linkedin.com/rest/images?action=initializeUpload",
        headers=_headers(access_token),
        json={"initializeUploadRequest": {"owner": person_urn}},
        timeout=30,
    )
    body = response.json()

    if response.status_code != 200 or "value" not in body:
        raise RuntimeError(f"Failed to initialize LinkedIn image upload (HTTP {response.status_code}): {body}")

    value = body["value"]
    return value["uploadUrl"], value["image"]


def upload_image_bytes(upload_url: str, access_token: str, image_path: str) -> None:
    with open(image_path, "rb") as f:
        response = requests.put(
            upload_url,
            headers={"Authorization": f"Bearer {access_token}"},
            data=f.read(),
            timeout=60,
        )

    if response.status_code not in (200, 201):
        raise RuntimeError(f"Failed to upload image bytes to LinkedIn (HTTP {response.status_code}): {response.text}")


def create_post(access_token: str, person_urn: str, image_urn: str, caption: str) -> str:
    response = requests.post(
        "https://api.linkedin.com/rest/posts",
        headers=_headers(access_token),
        json={
            "author": person_urn,
            "commentary": caption,
            "visibility": "PUBLIC",
            "distribution": {
                "feedDistribution": "MAIN_FEED",
                "targetEntities": [],
                "thirdPartyDistributionChannels": [],
            },
            "content": {"media": {"id": image_urn}},
            "lifecycleState": "PUBLISHED",
            "isReshareDisabledByAuthor": False,
        },
        timeout=30,
    )

    if response.status_code != 201:
        raise RuntimeError(f"Failed to create LinkedIn post (HTTP {response.status_code}): {response.text}")

    return response.headers.get("x-restli-id", "unknown")


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: python src/linkedin_post.py <image_path> <caption>", file=sys.stderr)
        return 1

    image_path, caption = sys.argv[1], sys.argv[2]

    load_dotenv()
    access_token = os.environ.get("LINKEDIN_ACCESS_TOKEN")

    if not access_token:
        print(
            "ERROR: LINKEDIN_ACCESS_TOKEN must be set (run src/linkedin_auth.py first).",
            file=sys.stderr,
        )
        return 1

    if not os.path.isfile(image_path):
        print(f"ERROR: image file not found: {image_path}", file=sys.stderr)
        return 1

    try:
        person_urn = get_person_urn(access_token)
        upload_url, image_urn = initialize_image_upload(access_token, person_urn)
        upload_image_bytes(upload_url, access_token, image_path)
        post_id = create_post(access_token, person_urn, image_urn, caption)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"SUCCESS: posted to LinkedIn profile {person_urn} — post id {post_id}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
